var tape = require("tape");

// Takes the specified *random* number generator and performs a Kolmogorov-
// Smirnov test which asserts that the values generated by said RNG could be
// generated by the distribution with cumulative distribution function *cdf*.
// Each test runs in O(n log n) * O(cdf). Passes with P ≈ 98%.
//
// https://en.wikipedia.org/wiki/Kolmogorov–Smirnov_test
tape.Test.prototype.kolmogorovSmirnov = function(random, cdf) {
  var i = -1,
      n = 1000,
      values = new Array(n),
      K_positive,
      K_min = 0.723255 - 0.794145, // See K-S test in Knuth’s AoCP Vol. 2.
      K_max = 0.723255 + 0.794145;

  while (++i < n) values[i] = random();
  values.sort(function(a, b) { return a - b; });

  i = -1, K_positive = -Infinity;
  while (++i < n) K_positive = Math.max(K_positive, (i / n) - cdf(values[i]));
  K_positive *= Math.sqrt(n);

  this._assert(K_min <= K_positive && K_positive <= K_max, {
    message: "should pass Kolmogorov-Smirnov",
    operator: "kolmogorovSmirnov",
    actual: K_positive,
    expected: [K_min, K_max]
  });
};
